version: 2

jobs:

  build:
    working_directory: ~/note
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      # <https://serverfault.com/a/84528>
      - run: echo "Europe/Berlin" > /etc/timezone
      - run: apt install -y make texlive-luatex texlive-science texlive-fonts-extra texlive-bibtex-extra biber
      - checkout
      - run: make
      - run: biber main
      - run: make
