version: 2

jobs:

  build:
    working_directory: ~/note
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt update
      - run: apt install -y texlive make
      - checkout
      - run: make
      - run: biber main
      - run: make
