version: 2

jobs:

  build:
    working_directory: ~/note
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      # <https://askubuntu.com/q/909277/75918>
      - run: apt install -y tzdata
      - run: apt install -y make texlive-luatex texlive-science texlive-fonts-extra texlive-bibtex-extra biber
      - checkout
      - run: make
      - run: biber main
      - run: make
