version: 2

jobs:

  build:
    working_directory: ~/note
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive apt install tzdata
      - run: apt install -y make texlive-luatex texlive-science texlive-fonts-extra texlive-bibtex-extra biber qpdf
      - checkout
      - run: make
      - run: biber main
      - run: make
